export { Header } from "./Header";
export { Footer } from "./Footer";
export { OurValuesSection } from "./OurValuesSection";
export { GradientBannerSection } from "./GradientBannerSection";
export { OurVisionOurMission as OurVisionOurMissionSection } from "./OurVisionOurMissionSection";
export { InfographSection } from "./InfographSection";
export { StatsSection } from "./StatsSection";
export { OurBrandsSection } from "./OurBrandsSection";
export { TimelineSection } from "./TimelineSection";
export { DoubleCardSection } from "./DoubleCardSection";
export { OurAwardsSection } from "./OurAwardsSection";
export { StayConnectedSection } from "./StayConnectedSection";
export { ContactUsSection } from "./ContactUsSection";
