export const pandaValueCardsData = [
  {
    title: "Ownership",
    text: "We believe ownership with passion are the fuel of excellence",
    img: "/img/ownership.svg",
  },
  {
    title: "Customer Excellence",
    text: "We believe that a happy customer is the best way to succeed",
    img: "/img/customer-experience.svg",
  },
  {
    title: "Teamwork",
    text: "We believe that everyone contributes to the worth of others",
    img: "/img/teamwork.svg",
  },
  {
    title: "Integrity",
    text: "We believe in succeeding with integrity",
    img: "/img/integrity.svg",
  },
  {
    title: "Agility",
    text: "We believe in agility to drive change",
    img: "/img/agility.svg",
  },
];

export const executiveTeam = [
  {
    name: "Abdullah Al Sabban",
    position: "Chief Operations Officer",
    img: "/img/Panda-Exec7079-Edit-scaled.jpg",
  },
  {
    name: "Eric Deliers",
    position: "Chief Commercial Officer",
    img: "/img/Panda-Exec7020-Edit-scaled.jpg",
  },
  {
    name: "Ryyan Tarabzoni",
    position: "Chief Supply Chain Officer & CEO Advisor",
    img: "/img/Panda-Exec7504-Edit-scaled.jpg",
  },
  {
    name: "Ahmed Chehade",
    position: "Chief Marketing Officer",
    img: "/img/Panda-Exec7118-Edit-scaled.jpg",
  },
  {
    name: "Fouad Reda",
    position: "Chief Business Support Officer",
    img: "/img/Fouad-Reda-scaled.jpg",
  },
  {
    name: "Mohammed Khorshid",
    position: "Chief Financial Officer",
    img: "/img/Panda-Exec7594-Edit-scaled.jpg",
  },
  {
    name: "Piyush Chowhan",
    position: "Chief Digital Officer",
    img: "/img/Panda-Exec7613-Edit-scaled.jpg",
  },
  {
    name: "Wassim Al Tahawi",
    position: "Chief Governance, Risk, and Compliance Officer",
    img: "/img/Panda-Exec7246-Edit-scaled.jpg",
  },
  {
    name: "Majid Basha",
    position: "Chief of Staff",
    img: "/img/Panda-Exec7332-Edit-scaled.jpg",
  },
  {
    name: "Hicham Aouda",
    position: "CEO Advisor for Business Development",
    img: "/img/MicrosoftTeams-image-1-1-scaled.jpg",
  },
  {
    name: "Bandar Al Saidi",
    position: "Vice President for Commercial Food",
    img: "/img/Bandar-alsaedi-Picture-scaled.jpg",
  },
  {
    name: "Hisham BaEissa",
    position: "Director of Board Governance & Secretary",
    img: "/img/Panda-Exec7383-Edit-scaled.jpg",
  },
];

export const stats = [
  {
    title: "11.9 Billion",
    text: "Sales across all our stores (2021)",
  },
  {
    title: "100+ Million",
    text: "Customer shopping at our stores every year",
  },
  {
    title: "17,000+",
    text: "Employees work with dedication and commitment",
  },
  {
    title: "188",
    text: "Stores across the Kingdom (Excluding Jamjom and Egypt)",
  },
  {
    title: "30,000+",
    text: "SKUs of products displayed at our stores ",
  },
  {
    title: "600+",
    text: "Distribution fleet of trucks with 4 main distribution centers across the Kingdom",
  },
];

export const awards = [
  {
    year: "2010",
    yearAwards: [
      {
        awardText: [
          {
            quoted: true,
            text: "Best Management Talent",
          },
          {
            quoted: false,
            text: "by a coalition of human resources leadership of the United Kingdom",
          },
        ],
      },
    ],
  },
  {
    year: "2011",
    yearAwards: [
      {
        awardText: [
          {
            quoted: true,
            text: "Asia’s Best Brand Awards",
          },
          {
            quoted: false,
            text: "in Singapore",
          },
        ],
      },
    ],
  },
  {
    year: "2012",
    yearAwards: [
      {
        awardText: [
          {
            quoted: true,
            text: "Brand Excellence in Retail Award",
          },
          {
            quoted: false,
            text: "by world conference of the brand",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: false,
            text: "1st Place",
          },
          {
            quoted: true,
            text: "Best Saudi Working Environment",
          },
          {
            quoted: false,
            text: "ranked in Eqtisadia Newspaper",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "Disabled Children Association Award",
          },
          {
            quoted: false,
            text: "for Leave the Change for Them initiative",
          },
        ],
      },
    ],
  },
  {
    year: "2013",
    yearAwards: [
      {
        awardText: [
          {
            quoted: true,
            text: "One of the Best 100 Brands",
          },
          {
            quoted: false,
            text: "Al-Watan Newspaper in collaboration with Ipsos Global",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "Global Brand Excellence Award",
          },
          {
            quoted: false,
            text: "generated by the word conference of the brand",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "Asian Leadership Award",
          },
          {
            quoted: false,
            text: "for the retail sector by ET NOW international",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "Best Employer in Middle East & North of Africa Region",
          },
          {
            quoted: false,
            text: "by Aon Hewitt",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "Asia’s Best Employer Awards",
          },
          {
            quoted: false,
            text: "by Company Consultant CMO in Singapore",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "The Saudi Award for Social Responsibility",
          },
          {
            quoted: false,
            text: ", as the best company in the Kingdom in the field of Social Responsibility by the Chamber of Commerce and Industry in Jeddah",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: false,
            text: "Achieved the second ranking for",
          },
          {
            quoted: true,
            text: "Best Social Responsibility initiatives",
          },
          {
            quoted: false,
            text: "for “my environment my friend ” Project in World Retail Congress in Paris",
          },
        ],
      },
    ],
  },
  {
    year: "2014",
    yearAwards: [
      {
        awardText: [
          {
            quoted: true,
            text: "Best Employer in Middle East & North of Africa Region",
          },
          {
            quoted: false,
            text: "by Aon Hewitt",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "Brand Excellence in Retail Award",
          },
          {
            quoted: false,
            text: "by CMO in Asia",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "Best Food Market Award",
          },
          {
            quoted: false,
            text: "for the best food retail market in Arab word",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "Best Saudi Working Environment",
          },
          {
            quoted: false,
            text: "ranked 6th in Eqtisadia Newspaper",
          },
        ],
      },
    ],
  },
  {
    year: "2015",
    yearAwards: [
      {
        awardText: [
          {
            quoted: true,
            text: "Brand Excellence in Retail Award",
          },
          {
            quoted: false,
            text: "by CMO in Asia",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "Sustainable Marketing Excellence Award",
          },
          {
            quoted: false,
            text: "by CMO in Asia",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "Best Use of Social Media in Marketing Award",
          },
          {
            quoted: false,
            text: "by CMO in Asia",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "Top 100 Brand",
          },
          {
            quoted: false,
            text: "in Saudi Arabia by Watan Newspaper in Riyadh",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "Best Retail Company",
          },
          {
            quoted: false,
            text: "by Arabian Business in Riyadh",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: false,
            text: "by Arabian Business in Riyadh",
          },
        ],
      },
    ],
  },
  {
    year: "2017",
    yearAwards: [
      {
        awardText: [
          {
            quoted: false,
            text: "Brand Impact Leader by Brand Z. number 1 as the Brand Impact Leader in Saudi Arabia and the 10th most valuable brand in Saudi Arabia by the first ever Brand Valuation Report in Saudi Arabia published by Prince Mohammad Bin Salman College",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: false,
            text: "Best Companies Award for Employees with Disability as the second foreign company given by the Government of Brazil in association with the United Nations",
          },
        ],
      },
    ],
  },
  {
    year: "2018",
    yearAwards: [
      {
        awardText: [
          {
            quoted: false,
            text: "Best Companies Award for Employees with Disability at the United Nations Headquarters in NY",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "Mowaamah Inclusion Certificate",
          },
          {
            quoted: false,
            text: "Ministry of Labor & Social Development awarded Panda its Gold standard Mowaamah Certificate. This was in recognition for its long-standing commitment as a disability friendly organization and for its programs and initiatives in relation to the employment of people with disabilities in the Kingdom.",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "Saudization Award",
          },
          {
            quoted: false,
            text: "His Highness Prince of Al-Qassim Region and His Excellency Minister of Labor & Social Development recognized Panda Retail Company with the Saudization Award for realizing 60% Saudization of staff in the Company’s stores across Al-Qassim Region.",
          },
        ],
      },
    ],
  },
  {
    year: "2020",
    yearAwards: [
      {
        awardText: [
          {
            quoted: true,
            text: "Awarded as one of the Most Supportive Brands in Saudi Arabia",
          },
          {
            quoted: false,
            text: "by IPSOS, a global leader in market research",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: true,
            text: "Awarded as one of the Most Valuable Brands in Saudi Arabia and United Arab Emirates",
          },
          {
            quoted: false,
            text: "by the world’s largest advertising group WPP and its subsidiary Kantar, a leading research, consumer insights and data company",
          },
        ],
      },
      {
        awardText: [
          {
            quoted: false,
            text: "Panda Click application won",
          },
          {
            quoted: true,
            text: "Bronze Award",
          },
          {
            quoted: false,
            text: "from Huawei Developers Competition",
          },
        ],
      },
    ],
  },
];
